### ISSUE TITLE
📝 Improvements tracker

### ISSUE THREAD

**Issue by NikolaLohinski** [NikolaLohinski/terraform-provider-jinja#6]
# 🚀 Features
_See https://github.com/NikolaLohinski/gonja/issues/3 for `gonja` related features_

<details>
  <summary>Click me to see finished work</summary>

- [x] `fromyaml`, `toyaml` filters
    (done in `v1.11.1`)
- [x]  `dir`, basename would be good too
    (done in `v1.11.1`)
- [x] `fromtoml`, `totoml` filters
    (done in `v1.13.0`)
- [x] An `file` filter to load the content of a file into a variable, similarly to the `include` statement 
    (done in `v1.12.0`)
- [x] Document gonja builtin statements, filters and globals in the provider docs
    (done in `v1.12.0`)
- [x] Move all filters to gonja itself (since it's now a fully maintained fork)
    (done in `v1.12.0`)
- [x] Add the ability to specify the working directory when dealing with inlined templates
   (done in `v1.16.0` )

- [x] Move to the [terraform plugin framework](https://developer.hashicorp.com/terraform/plugin/framework)
   (Done in `v2.0.0`)
</details>

# 🐛 Bug fixes

<details>
  <summary>Click me to see finished work</summary>

- [x] The `split` filter is buggy: `"test_foo" | split("_") | last` is not behaving as expected
    (done in `v1.11.1`) 
- [x] Native gonja filter `length` is broken for objects
    (done in `v1.12.0`)
- [x] Native gonja filters such as `select` or `selectattr` are broken when it comes to the type they are returning and need to be fixed in gonja itself. 
    <details>
    <summary>Details</summary>
       
    For example:
       
    ```
    {{- [{"a": 1}, {"a": 2}] | selectattr("a", "==", 1) | first -}}
    ```
    does not work.
    
    </details>
    
    (done in `v1.12.0`)
        
- [x] There's a bug most likely in gonja itself when it comes to indent trimmers.
    <details>
    <summary>Details</summary>
    
    ```
    # [% if data.nope is defined -%]
    [% endif %]
    Should not be commented
    ````
    Renders as:
    ```
    # Should not be commented
    ```
    Instead of:
    ```
    # 
    Should not be commented
    ```
    when the variable is undefined
    </details>
    
    (done in `v1.12.0`)

- [x] Comments don't seem to handle correctly whitespace control using `-` 
    (done in `v1.13.0`)

</details>

**Comment by NikolaLohinski** [comment]
Leaving `merge` , `fromtoml` and `totoml`aside for now, the others are done in `v1.11.0`

**Comment by NikolaLohinski** [comment]
There's a bug in most likely in gonja itself when it comes to indent trimmers:

```
# [% if data.nope is defined -%]
[% endif %]
Should not be commented
```
Renders as:
```
# Should not be commented
```
Instead of:
```
# 
Should not be commented
```
when the variable is undefined

**Comment by NikolaLohinski** [comment]
- [ ] `working_directory` feature introduced in `v1.16.0` is not behaving correctly
